version: 2

use_cases:
- name: validation
  sections:
    - name: Example section
      description: "An example resource widget with query"
      key: resource_widget_example
      widget: cy_inventory_resource
      type: string
      widget_config:
      attribute: id
    - name: Example
      technologies: [pipeline]
      vars:
        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test-no-validation"
          name: "array"
          widget_config:
              multiselect: true

        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test"
          name: "array variable"
          widget_config:
              multiselect: true
          validations:
            - array:
                must_exist_elems: [["lb1", 32223]]
              error_message: 'lb1 must be present'
            - array:
                max_elems: 2
- name: validation2
  sections:
  - name: Example section
    groups:
    - name: Example group2
      technologies: [pipeline]
      vars:
        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test-no-validation"
          name: "array variable"
          widget_config:
              multiselect: true

        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test"
          name: "array variable"
          widget_config:
              multiselect: true
          validations:
            - array:
                must_exist_elems: [["lb1", 32223]]
              error_message: 'lb1 must be present'
            - array:
                max_elems: 2
